<?php

namespace admin\Entity;

/**
 * AgentAmountAdjust
 *
 * @package admin\Entity
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-07-13, 12:10:41
 */

abstract class AbstractEntity extends \Phalcon\Mvc\Model
{

}